  name: Package Jar
  
  on:
    release:
      types: [published]
   
  jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
          
        - name: Build with Gradle
          run: ./gradlew build -PfileName=Worttrainer-${{ github.event.release.tag_name }}.jar
          
        - name: Archive Jar
          uses: actions/upload-artifact@v4
          with:
            name: Worttrainer-${{ github.event.release.tag_name }}.jar
            path: build/libs/Worttrainer-${{ github.event.release.tag_name }}.jar
        
        - name: Upload JAR to Release
          uses: actions/upload-release-asset@latest
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./build/libs/Worttrainer-${{ github.event.release.tag_name }}.jar
            asset_name: Worttrainer-${{ github.event.release.tag_name }}.jar
            #asset_path: ./Worttrainer-${{ github.event.release.tag_name }}.jar
            #asset_name: Worttrainer-${{ github.event.release.tag_name }}.jar
            asset_content_type: application/java-archive
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    