  name: Package Jar
  
  on:
    release:
      types: [published]
   
  jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout
          
        - name: Set up JDK 21
          uses: actions/setup-java
          with:
            distribution: 'temurin'
            java-version: '21'
            
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
          
        - name: Build with Gradle
          run: ./gradlew build
          
        - name: Archive Jar
          uses: actions/upload-artifact
          with:
            name: Worttrainer.jar
            path: build/libs/*.jar
        
        - name: Upload JAR to Release
          uses: actions/upload-release-asset
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: build/libs/*.Jar
            asset_name: Worttrainer-${{ github.event.release.tag_name }}.jar
            asset_content_type: application/java-archive

    